[package]
name = "rusca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.4"
regex = "1.7.0"
memmap2 = "0.5.8"
clap = {version = "3.0.5", features=["cargo"]}
